# lista de paquetes a instalar en el sistema y para PHP
SYSTEM_PACKAGES=(
    "git"
    "curl"
    "wget"
    "zip"
    "unzip"
    "ca-certificates"
    "gnupg"
    "lsb-release"
)

PHP_PACKAGES=(
    "php8.3"
    "php8.3-cli"
    "php8.3-common"
    "php8.3-mysql"
    "php8.3-xml"
    "php8.3-curl"
    "php8.3-mbstring"
    "php8.3-zip"
    "php8.3-bcmath"
    "php8.3-intl"
    "php8.3-sqlite3"
)