# Definición centralizada de colores para que los script se vean mamalones
COLOR_PRIMARY="\033[0;34m" # color azul
COLOR_SUCCESS="\033[0;32m" # color verde
COLOR_WARNING="\033[1;33m" # color amarillo
COLOR_DANGER="\033[0;31m" # color rojo
COLOR_RESET="\033[0m" # restablecer color